Class HL7v2Template.Test.CodeSet.RepeatPattern Extends (%Persistent, HL7v2Template.DT.CodeSet)
{

Index CodeIndex On Code [ IdKey, Unique ];

Storage Default
{
<Data name="RepeatPatternDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Text</Value>
</Value>
<Value name="3">
<Value>System</Value>
</Value>
</Data>
<DataLocation>^HL7v2Templat9F11.RepeatPatternD</DataLocation>
<DefaultData>RepeatPatternDefaultData</DefaultData>
<IdLocation>^HL7v2Templat9F11.RepeatPatternD</IdLocation>
<IndexLocation>^HL7v2Templat9F11.RepeatPatternI</IndexLocation>
<StreamLocation>^HL7v2Templat9F11.RepeatPatternS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
